version: 0.4.{build}

environment:
  matrix:
    - nodejs_version: 6.11.1
      POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

platform:
  - x64

services:
  - postgresql96

cache:
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%


install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install --force --no-lockfile
  - yarn run rebuild:modules:electron

build_script:
  - yarn run build
  - yarn run package

after_build:
  - 7z a release.zip release

artifacts:
  - path: release.zip
    name: release

test: off
